### PR TITLE
Add a working example to demo create-react-context

### PR DESCRIPTION
**Pull request by pksjce**

### CODE REVIEW

**Comment by thejameskyle** [comment]
Can you add the bundle to `.gitignore`

**Comment by thejameskyle** [comment]
And the package-lock

**Comment by thejameskyle** [comment]
Also, could you update the prettier format/lint-staged config in `package.json` to include all your files and run `yarn format` over them?

**Comment by pksjce** [comment]
Done! I just added another example to show that more components can accept the context. 

What we really need is for an example that is able to bypass `shouldComponentUpdate` check. Will you be implementing that?

**Comment by thejameskyle** [comment]
> What we really need is for an example that is able to bypass shouldComponentUpdate check. Will you be implementing that?

Yeah I just added that in the latest version

**Pull request merged**
